load('1.mat');
t2 = 0;
t1 = 0;
t2 = t2 + size(find(segmentation == 2),1);
t1 = t1 + size(find(segmentation == 1),1);
load('34.mat');
t2 = t2 + size(find(segmentation == 2),1);
t1 = t1 + size(find(segmentation == 1),1);
load('33.mat');
t2 = t2 + size(find(segmentation == 2),1);
t1 = t1 + size(find(segmentation == 1),1);
load('32.mat');
t2 = t2 + size(find(segmentation == 2),1);
t1 = t1 + size(find(segmentation == 1),1);
load('31.mat');
t2 = t2 + size(find(segmentation == 2),1);
t1 = t1 + size(find(segmentation == 1),1);
load('30.mat');
t2 = t2 + size(find(segmentation == 2),1);
t1 = t1 + size(find(segmentation == 1),1);
load('29.mat');
t2 = t2 + size(find(segmentation == 2),1);
t1 = t1 + size(find(segmentation == 1),1);
load('28.mat');
t2 = t2 + size(find(segmentation == 2),1);
t1 = t1 + size(find(segmentation == 1),1);
load('27.mat');
t2 = t2 + size(find(segmentation == 2),1);
t1 = t1 + size(find(segmentation == 1),1);
load('26.mat');
t2 = t2 + size(find(segmentation == 2),1);
t1 = t1 + size(find(segmentation == 1),1);
load('25.mat');
t2 = t2 + size(find(segmentation == 2),1);
t1 = t1 + size(find(segmentation == 1),1);
load('24.mat');
t2 = t2 + size(find(segmentation == 2),1);
t1 = t1 + size(find(segmentation == 1),1);
load('23.mat');
t2 = t2 + size(find(segmentation == 2),1);
t1 = t1 + size(find(segmentation == 1),1);
load('22.mat');
t2 = t2 + size(find(segmentation == 2),1);
t1 = t1 + size(find(segmentation == 1),1);
load('21.mat');
t2 = t2 + size(find(segmentation == 2),1);
t1 = t1 + size(find(segmentation == 1),1);
load('20.mat');
t2 = t2 + size(find(segmentation == 2),1);
t1 = t1 + size(find(segmentation == 1),1);
load('19.mat');
t2 = t2 + size(find(segmentation == 2),1);
t1 = t1 + size(find(segmentation == 1),1);
load('18.mat');
t2 = t2 + size(find(segmentation == 2),1);
t1 = t1 + size(find(segmentation == 1),1);
load('17.mat');
t2 = t2 + size(find(segmentation == 2),1);
t1 = t1 + size(find(segmentation == 1),1);
load('16.mat');
t2 = t2 + size(find(segmentation == 2),1);
t1 = t1 + size(find(segmentation == 1),1);
load('15.mat');
t2 = t2 + size(find(segmentation == 2),1);
t1 = t1 + size(find(segmentation == 1),1);
load('14.mat');
t2 = t2 + size(find(segmentation == 2),1);
t1 = t1 + size(find(segmentation == 1),1);
load('13.mat');
t2 = t2 + size(find(segmentation == 2),1);
t1 = t1 + size(find(segmentation == 1),1);
load('12.mat');
t2 = t2 + size(find(segmentation == 2),1);
t1 = t1 + size(find(segmentation == 1),1);
load('11.mat');
t2 = t2 + size(find(segmentation == 2),1);
t1 = t1 + size(find(segmentation == 1),1);
load('10.mat');
t2 = t2 + size(find(segmentation == 2),1);
t1 = t1 + size(find(segmentation == 1),1);
load('9.mat');
t2 = t2 + size(find(segmentation == 2),1);
t1 = t1 + size(find(segmentation == 1),1);
load('8.mat');
t2 = t2 + size(find(segmentation == 2),1);
t1 = t1 + size(find(segmentation == 1),1);
load('7.mat');
t2 = t2 + size(find(segmentation == 2),1);
t1 = t1 + size(find(segmentation == 1),1);
load('6.mat');
t2 = t2 + size(find(segmentation == 2),1);
t1 = t1 + size(find(segmentation == 1),1);
load('5.mat');
t2 = t2 + size(find(segmentation == 2),1);
t1 = t1 + size(find(segmentation == 1),1);
load('4.mat');
t2 = t2 + size(find(segmentation == 2),1);
t1 = t1 + size(find(segmentation == 1),1);
load('3.mat');
t2 = t2 + size(find(segmentation == 2),1);
t1 = t1 + size(find(segmentation == 1),1);
load('2.mat');
t2 = t2 + size(find(segmentation == 2),1);
t1 = t1 + size(find(segmentation == 1),1);
load('35.mat');
t2 = t2 + size(find(segmentation == 2),1);
t1 = t1 + size(find(segmentation == 1),1);
load('36.mat');
t2 = t2 + size(find(segmentation == 2),1);
t1 = t1 + size(find(segmentation == 1),1);
load('37.mat');
t2 = t2 + size(find(segmentation == 2),1);
t1 = t1 + size(find(segmentation == 1),1);
load('38.mat');
t2 = t2 + size(find(segmentation == 2),1);
t1 = t1 + size(find(segmentation == 1),1);
load('39.mat');
t2 = t2 + size(find(segmentation == 2),1);
t1 = t1 + size(find(segmentation == 1),1);
load('40.mat');
t2 = t2 + size(find(segmentation == 2),1);
t1 = t1 + size(find(segmentation == 1),1);
load('41.mat');
t2 = t2 + size(find(segmentation == 2),1);
t1 = t1 + size(find(segmentation == 1),1);
load('42.mat');
t2 = t2 + size(find(segmentation == 2),1);
t1 = t1 + size(find(segmentation == 1),1);
load('43.mat');
t2 = t2 + size(find(segmentation == 2),1);
t1 = t1 + size(find(segmentation == 1),1);
load('44.mat');
t2 = t2 + size(find(segmentation == 2),1);
t1 = t1 + size(find(segmentation == 1),1);
load('45.mat');
t2 = t2 + size(find(segmentation == 2),1);
t1 = t1 + size(find(segmentation == 1),1);
load('46.mat');
t2 = t2 + size(find(segmentation == 2),1);
t1 = t1 + size(find(segmentation == 1),1);
load('47.mat');
t2 = t2 + size(find(segmentation == 2),1);
t1 = t1 + size(find(segmentation == 1),1);
load('48.mat');
t2 = t2 + size(find(segmentation == 2),1);
t1 = t1 + size(find(segmentation == 1),1);
load('49.mat');
t2 = t2 + size(find(segmentation == 2),1);
t1 = t1 + size(find(segmentation == 1),1);
load('50.mat');
t2 = t2 + size(find(segmentation == 2),1);
t1 = t1 + size(find(segmentation == 1),1);


load('51.mat');
t2 = t2 + size(find(segmentation == 2),1);
t1 = t1 + size(find(segmentation == 1),1);
load('52.mat');
t2 = t2 + size(find(segmentation == 2),1);
t1 = t1 + size(find(segmentation == 1),1);
load('53.mat');
t2 = t2 + size(find(segmentation == 2),1);
t1 = t1 + size(find(segmentation == 1),1);
load('54.mat');
t2 = t2 + size(find(segmentation == 2),1);
t1 = t1 + size(find(segmentation == 1),1);
load('55.mat');
t2 = t2 + size(find(segmentation == 2),1);
t1 = t1 + size(find(segmentation == 1),1);
load('56.mat');
t2 = t2 + size(find(segmentation == 2),1);
t1 = t1 + size(find(segmentation == 1),1);
load('57.mat');
t2 = t2 + size(find(segmentation == 2),1);
t1 = t1 + size(find(segmentation == 1),1);
load('58.mat');
t2 = t2 + size(find(segmentation == 2),1);
t1 = t1 + size(find(segmentation == 1),1);
load('59.mat');
t2 = t2 + size(find(segmentation == 2),1);
t1 = t1 + size(find(segmentation == 1),1);
load('60.mat');
t2 = t2 + size(find(segmentation == 2),1);
t1 = t1 + size(find(segmentation == 1),1);
load('61.mat');
t2 = t2 + size(find(segmentation == 2),1);
t1 = t1 + size(find(segmentation == 1),1);
load('62.mat');
t2 = t2 + size(find(segmentation == 2),1);
t1 = t1 + size(find(segmentation == 1),1);
load('63.mat');
t2 = t2 + size(find(segmentation == 2),1);
t1 = t1 + size(find(segmentation == 1),1);
load('64.mat');
t2 = t2 + size(find(segmentation == 2),1);
t1 = t1 + size(find(segmentation == 1),1);
load('65.mat');
t2 = t2 + size(find(segmentation == 2),1);
t1 = t1 + size(find(segmentation == 1),1);
load('66.mat');
t2 = t2 + size(find(segmentation == 2),1);
t1 = t1 + size(find(segmentation == 1),1);
load('67.mat');
t2 = t2 + size(find(segmentation == 2),1);
t1 = t1 + size(find(segmentation == 1),1);
load('68.mat');
t2 = t2 + size(find(segmentation == 2),1);
t1 = t1 + size(find(segmentation == 1),1);
load('69.mat');
t2 = t2 + size(find(segmentation == 2),1);
t1 = t1 + size(find(segmentation == 1),1);
load('70.mat');
t2 = t2 + size(find(segmentation == 2),1);
t1 = t1 + size(find(segmentation == 1),1);
load('71.mat');
t2 = t2 + size(find(segmentation == 2),1);
t1 = t1 + size(find(segmentation == 1),1);
load('72.mat');
t2 = t2 + size(find(segmentation == 2),1);
t1 = t1 + size(find(segmentation == 1),1);
load('73.mat');
t2 = t2 + size(find(segmentation == 2),1);
t1 = t1 + size(find(segmentation == 1),1);
load('74.mat');
t2 = t2 + size(find(segmentation == 2),1);
t1 = t1 + size(find(segmentation == 1),1);
load('75.mat');
t2 = t2 + size(find(segmentation == 2),1);
t1 = t1 + size(find(segmentation == 1),1);
load('76.mat');
t2 = t2 + size(find(segmentation == 2),1);
t1 = t1 + size(find(segmentation == 1),1);
load('77.mat');
t2 = t2 + size(find(segmentation == 2),1);
t1 = t1 + size(find(segmentation == 1),1);
load('78.mat');
t2 = t2 + size(find(segmentation == 2),1);
t1 = t1 + size(find(segmentation == 1),1);
load('79.mat');
t2 = t2 + size(find(segmentation == 2),1);
t1 = t1 + size(find(segmentation == 1),1);
load('80.mat');
t2 = t2 + size(find(segmentation == 2),1);
t1 = t1 + size(find(segmentation == 1),1);
load('81.mat');
t2 = t2 + size(find(segmentation == 2),1);
t1 = t1 + size(find(segmentation == 1),1);
load('82.mat');
t2 = t2 + size(find(segmentation == 2),1);
t1 = t1 + size(find(segmentation == 1),1);
load('83.mat');
t2 = t2 + size(find(segmentation == 2),1);
t1 = t1 + size(find(segmentation == 1),1);
load('84.mat');
t2 = t2 + size(find(segmentation == 2),1);
t1 = t1 + size(find(segmentation == 1),1);
load('85.mat');
t2 = t2 + size(find(segmentation == 2),1);
t1 = t1 + size(find(segmentation == 1),1);
load('86.mat');
t2 = t2 + size(find(segmentation == 2),1);
t1 = t1 + size(find(segmentation == 1),1);
load('87.mat');
t2 = t2 + size(find(segmentation == 2),1);
t1 = t1 + size(find(segmentation == 1),1);
load('88.mat');
t2 = t2 + size(find(segmentation == 2),1);
t1 = t1 + size(find(segmentation == 1),1);
load('89.mat');
t2 = t2 + size(find(segmentation == 2),1);
t1 = t1 + size(find(segmentation == 1),1);
load('90.mat');
t2 = t2 + size(find(segmentation == 2),1);
t1 = t1 + size(find(segmentation == 1),1);
load('91.mat');
t2 = t2 + size(find(segmentation == 2),1);
t1 = t1 + size(find(segmentation == 1),1);
load('92.mat');
t2 = t2 + size(find(segmentation == 2),1);
t1 = t1 + size(find(segmentation == 1),1);
load('93.mat');
t2 = t2 + size(find(segmentation == 2),1);
t1 = t1 + size(find(segmentation == 1),1);
load('94.mat');
t2 = t2 + size(find(segmentation == 2),1);
t1 = t1 + size(find(segmentation == 1),1);
load('95.mat');
t2 = t2 + size(find(segmentation == 2),1);
t1 = t1 + size(find(segmentation == 1),1);
load('96.mat');
t2 = t2 + size(find(segmentation == 2),1);
t1 = t1 + size(find(segmentation == 1),1);
load('97.mat');
t2 = t2 + size(find(segmentation == 2),1);
t1 = t1 + size(find(segmentation == 1),1);
load('98.mat');
t2 = t2 + size(find(segmentation == 2),1);
t1 = t1 + size(find(segmentation == 1),1);
load('99.mat');
t2 = t2 + size(find(segmentation == 2),1);
t1 = t1 + size(find(segmentation == 1),1);
load('100.mat');
t2 = t2 + size(find(segmentation == 2),1);
t1 = t1 + size(find(segmentation == 1),1);

rightsum = t2/100;
leftsum = t1/100;